# all jobs must pass on both the `staging` commit and the PR’s CI
# before merging
pr_status = [
  "Rust (ubuntu-latest)",
  "Rust (windows-latest)",
  "Rust (macos-latest)",
  "Formatting",
]
status = [
  "Rust (ubuntu-latest)",
  "Rust (windows-latest)",
  "Rust (macos-latest)",
  "Formatting",
]

delete_merged_branches = true 
required_approvals = 1 
timeout_sec = 600 # CI must take at most ten minutes
use_squash_merge = true
